### ISSUE TITLE
Do not see plugin at all

### ISSUE THREAD

**Issue by martan3d** [fog/fog-proxmox#40]
This does not install as a plugin and does not register as such.  Perhaps the docs can be expanded a bit to guide the newbies.  If I could provision a host on Proxmox I would be very happy.  Many people I know would also be happy.

**Comment by pescobar** [comment]
I have installed these rpms:

```
foreman-1.20.1-1.el7.noarch
katello-3.10.0-0.6.rc1.el7.noarch
tfm-rubygem-fog-proxmox-doc-0.5.2-1.el7.noarch
```

but when I go to `administer >> about >> plugins` in the foreman webui I cannot see the plugin at all. 

I also get this error in the shell when trying to do `irb` and ` require 'fog/proxmox'`

```
[root@katello]# irb

irb(main):001:0> require 'fog/proxmox'

LoadError: cannot load such file -- fog/proxmox
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /bin/irb:12:in `<main>'
irb(main):002:0> 
```

**Comment by martan3d** [comment]
My take on this (so far) is that this is a 'fog' level sort of subsystem only. You have to write the actual plugin yourself on top of this framework.  Not like the docs mention that eh?  Anyhow, I have had some success in making a proxmox plugin register and then having it as 'computer resource' that I can use when I configure a host.  However when I hit the 'build' button it goes off in the weeds and I'm stuck after that.

**Comment by tristanrobert** [comment]
You should try using this archive: http://yum.theforeman.org/plugins/latest/el7/x86_64/tfm-rubygem-fog-proxmox-0.5.2-1.el7.noarch.rpm and not the doc.

**Comment by pescobar** [comment]
hi @tristanrobert that was a mistake when I copied the list of installed rpms. I had installed both packages `tfm-rubygem-fog-proxmox-0.5.2-1.el7.noarch.rpm` and `tfm-rubygem-fog-proxmox-doc-0.5.2-1.el7.noarch` but still I cannot see the plugin

I have updated my original comment with the proper rpm name

**Comment by hlawatschek** [comment]
Hi! If you want to use this in Foreman, you also need to install tfm-rubygem-foreman_fog_proxmox ;-)

**Comment by martan3d** [comment]
Just a note- I am a rank beginner in Ruby on Rails so a sort of step by step to get this into Foreman and running would be very helpful.  I will do a re-install on a fresh foreman instance with the above information and try again- Thanks.
