### ISSUE TITLE
Question regarding License

### ISSUE THREAD

**Issue by chessbyte** [fog/fog-proxmox#73]
Is there a reason why this project is licensed as GPLv3, whereas https://github.com/fog/fog is MIT?

**Comment by weismannweb** [comment]
+1

**Comment by stiwa-wrre** [comment]
@tristanrobert @Manisha15  Hi, is there any reason to keep it GPL?

Who is the current owner of this repo, to make a change in the license?

We would kindly ask to change it to MIT, because we want to build a Proxmox Provider for ManageIQ. Proxmox sees a great increase in usage because of the latest and greatest changes of VMWare.

Maybe we can also give this project more live again....

Thanks in regard :)

**Comment by Manisha15** [comment]
@tristanrobert @ekohl since you also contributed to the repository, what do you think of changing the license from GPLv3 to MIT?

**Comment by stiwa-wrre** [comment]
Is there any update on this? @Manisha15

**Comment by ekohl** [comment]
I missed this notification, but I have no objection to changing the license from GPLv3 to MIT.

@tristanrobert wrote a huge part of this project so I think his approval is much more important than mine. I can only speak for myself, but an email is much harder to miss than a GitHub notification. Has anyone tried that?

**Comment by tristanrobert** [comment]
Hello, sorry but I disagree changing license. GPLv3 is aimed at protecting this open source code. It is very important.

**Comment by davispuh** [comment]
> Hello, sorry but I disagree changing license. GPLv3 is aimed at protecting this open source code. It is very important.

I don't think you understand the implications of GPL license for a library. It requires anyone who uses/imports this gem to also license their whole app as GPL which basically means there's very few users who would want to use it. With such license most people will just rewrite this functionality and it's not even that much of work so essentially you're dooming this project to fail with very few contributors.

If you don't like MIT license then consider LGPL as that wouldn't require library users to license their whole app as GPL.

**Comment by davispuh** [comment]
Take a look at this comment  https://github.com/ManageIQ/manageiq/issues/21635#issuecomment-2396663098 and this is exactly what I thought will happen and I would contribute to such gem instead aswell.
