### ISSUE TITLE
Ask for merge permissions

### ISSUE THREAD

**Issue by Manisha15** [fog/fog-proxmox#86]
Atix team is actively working on Proxmox with Foreman 3.3+ and with recent version of Proxmox. I also have a PR in fog-proxmox: https://github.com/fog/fog-proxmox/pull/85

 I already have merge permissions for foreman_fog_proxmox (proxmox plugin for foreman), thanks to @ekohl. And now I want to fix some issues in fog-proxmox as well to restore the compatibility of Foreman with the new version of proxmox.. Since this repository is not maintained actively, @geemus if you don't object, it would be great if I can get merge permissions.

Thanks for considering.

**Comment by ekohl** [comment]
@geemus I can confirm that @Manisha15 is working on this and support granting access.

**Comment by geemus** [comment]
Sounds good, I've invited @Manisha15 to join the team.
