### ISSUE TITLE
Ask for merge permissions

### ISSUE THREAD

**Issue by Manisha15** [fog/fog-proxmox#90]
Atix team is actively working on Proxmox with Foreman 3.3+ and with recent version of Proxmox. I already have the merge rights and I would be glad if my colleague @sbernhard can also get the merge rights. Since merging the PR needs approval from one the members with write access, therefore, two colleagues from our team having merge write will make it easy for our team to contribute in a better and faster way.

Since this repository is not maintained actively, @geemus if you don't object, it would be great if @sbernhard  can get merge permissions.

Thanks for considering.

**Comment by geemus** [comment]
Sounds good, I've sent @sbernhard an invite.

**Comment by Manisha15** [comment]
> Sounds good, I've sent @sbernhard an invite.

Thank you so much.

**Comment by sbernhard** [comment]
Thanks @geemus 
Unfortunately, I can not find the invitation. Can you send it to me again, please?

**Comment by geemus** [comment]
@sbernhard I've sent another one.

**Comment by sbernhard** [comment]
sorry. Had an issue with my mail setup. Can you please send the invitation again? Thank you so much @geemus

**Comment by geemus** [comment]
Sent

**Comment by sbernhard** [comment]
Thanks. Works :-)
